# Generated by Django 3.2.7 on 2021-10-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hufgame',
            old_name='userid',
            new_name='username',
        ),
    ]
