# Generated by Django 3.2.7 on 2021-10-12 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameapi', '0002_rename_userid_hufgame_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hufgame',
            name='username',
            field=models.ForeignKey(db_column='username', default='deleted_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
