# Generated by Django 3.2.7 on 2021-10-12 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='HufGame',
        ),
        migrations.RemoveField(
            model_name='hufquizoption',
            name='quiz_qn',
        ),
        migrations.RemoveField(
            model_name='hufquizresult',
            name='quizid',
        ),
        migrations.RemoveField(
            model_name='hufuserans',
            name='userid',
        ),
        migrations.DeleteModel(
            name='HufQuiz',
        ),
        migrations.DeleteModel(
            name='HufQuizOption',
        ),
        migrations.DeleteModel(
            name='HufQuizQn',
        ),
        migrations.DeleteModel(
            name='HufQuizResult',
        ),
        migrations.DeleteModel(
            name='HufUser',
        ),
        migrations.DeleteModel(
            name='HufUserAns',
        ),
    ]
