export const mockGames = [
  {
    title: 'game1',
    creator: 'Song Yu',
    tags: [
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
      'Math',
    ],
  },
  {
    title: 'game2',
    creator: 'Song Yu',
    tags: ['Math'],
  },
  {
    title: 'game3',
    creator: 'Song Yu',
    tags: ['Math'],
  },
  {
    title: 'game4',
    creator: 'Song Yu',
    tags: ['Math'],
  },
  {
    title: 'game4',
    creator: 'Song Yu',
    tags: ['Math'],
  },
  {
    title: 'game',
    creator: 'Song Yu',
    tags: ['Math'],
  },
  {
    title: 'game1',
    creator: 'Song Yu',
    tags: ['Math'],
  },
  {
    title: 'game1',
    creator: 'Song Yu',
    tags: ['Math'],
  },
  {
    title: 'game1',
    creator: 'Song Yu',
    tags: ['Math'],
  },
  {
    title: 'game1',
    creator: 'Song Yu',
    tags: ['Math'],
  },
  {
    title: 'game1',
    creator: 'Song Yu',
    tags: ['Math'],
  },
  {
    title: 'game1',
    creator: 'Song Yu',
    tags: ['Math'],
  },
];
